MainApp/urls.py
from django.urls import path

from . import views

app_name = 'MainApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('Pizzas', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/',views.pizzas,name='pizza')

]

Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MainApp.urls')),
    #path('users/',include('users.urls')),
]

MainApp/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Topings(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

MainApp/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'MainApp/index.html')

from .models import Pizza

def pizzas(request):
    pizzas = Pizza.objects.filter(owner=request.user).order_by('date_added')
    context = {'pizzas':pizzas}

    return render(request, 'MainApp/pizzas.html',context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.toppings_set.order_by('-date_added')
    comments = pizza.comment_set.order_by('-date_added')

    context = {'pizza': pizza, 'toppings': toppings, 'comments': comments}
    return render(request, 'pizzas/pizzas.html', context)

MainApp/templates/mainapp/base.html
<p>
    <a href="{% url 'MainApp:index' %}">Pizzeria</a>
    <a href="{% url 'MainApp:pizzas' %}">Pizzas</a>
</p>



{% block content %}

{% endblock content %} 

MainApp/templates/mainapp/index.html
{% extends "MainApp/base.html" %} 

{% block content %} 
<p>
    Welcome to the pizzeria! Choose a pizza!

</p>
{% endblock content %}

MainApp/templates/mainapp/pizza.html
{% extends "MainApp/base.html" %} 

{% block content % }

<p>Pizza {{ Pizza }} </p>

<ul>

    {% for t in toppings %} 
    <li>
        <p>{{ topping.name|linebreaks}}</p>

    </li>

    {% empty %} 
        <li> There are no toppings for this Pizza</li>


</ul>

{% endblock content %}

MainApp/templates/mainapp/pizzas.html
{% entends "MainApp/base.html" %} 

{% block content %} 
    <p>Pizzas</p>



    <ul>


        {% for p pizzas %} 
            <li> <a href="{% url 'MainApp:pizza pizza.id %'}">{{ Pizza }}</a></li>

        {% empty %} 
            <li> No Pizzas have been added yet.</li>
        {% endfor %} 
    </ul>

{% endblock content %}